version: '3.3'
services:
  app:
    build: ./ops/Dockerfile
    volumes:
      - .:/code
    ports:
      - "3010"
      - "8000:8000"
    environment:
      PRODUCTION: 'true'
      DEBUG: 'False'
    entrypoint: /bin/bash
    command: -c "sleep infinity"

  web:
    image: nginx:latest
    volumes:
      - .:/code
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - app

